//"'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
//" Script Title       : 
//" Script Description : 
//"                      
//"                      
//" Script Author      : Myles
//" Script Date        : Thu May 26 11:33:29 2022
//" Generated By       : LoadRunner Recorder (Build: 0)
//"'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

function vuser_init()
{
	return 0;
}

